### ISSUE TITLE
Need a script to build and run all Java demos

### ISSUE THREAD

**Issue by sqlparser** [sqlparser/gsp_demo#4]
Need a script to build and run all Java demos

**Comment by sqlparser** [comment]
Please create compile and run bat under each demo directory

Take this for reference:
compile_checksyntax.bat, run_checksyntax.bat under
https://github.com/sqlparser/gsp_demo/blob/master/java/src/demos/checksyntax/

**Comment by cnfree** [comment]
Implemented it.
