### ISSUE TITLE
.net version can't install to   .NET Standard project

### ISSUE THREAD

**Issue by rustbomber** [sqlparser/gsp_demo#5]
I have .NET Standard class project, I want to install gap  3.3.0.2,is not success.

**Comment by tangdf** [comment]
.Net Version，the targetFramework  should be netstandard2.0，not netcoreapp.

**Comment by sqlparser** [comment]
@akaylh , .NET Standard project is not supported yet.

**Comment by sqlparser** [comment]
@tangdf Thanks for your participation, If you are interested in this project please contact me for further information.

**Comment by tangdf** [comment]
I do not understand why not support.
